version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - lib_data:/var/www/html/lib
      - cache_data:/var/www/html/src/cache

volumes:
  lib_data:
  cache_data: